'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.join(__dirname,'..');
const read=p=>fs.readFileSync(path.join(root,p),'utf8');

test('portal accessibility and delivery audit stays clean',()=>{
  const html=read('public/index.html');
  const css=read('public/index.css');
  const workspaceCss=read('public/portal-workspace.css');
  const tokensCss=read('public/ipt-tokens.css');
  const liquidCss=read('public/portal-liquid-glass.css');
  const homePracticeCss=read('public/portal-home-practice.css');
  const insightsCss=read('public/portal-insights.css');
  const vocabLibraryCss=read('public/portal-vocab-library.css');
  const writingMotionCss=read('public/portal-writing-motion.css');
  const writingMotion=read('public/portal-writing-motion.js');
  const portalShell=read('public/portal-shell.js');
  const personalAssistant=read('public/personal-ai-assistant.js');
  const personalAssistantCss=read('public/personal-ai-assistant.css');
  const interventionsClient=read('public/interventions-client.js');
  const portal=read('public/index.js');
  const reading=read('public/reading-practice.js');
  const lab=read('public/writing-lab-client.js');
  const server=read('server.js');
  const build=read('scripts/build-frontend.js');

  assert.equal((html.match(/<h1\b/g)||[]).length,1,'keep one application-level h1');
  assert.doesNotMatch(html,/<iframe\b/i);
  assert.doesNotMatch(html,/\sstyle="/i);
  assert.doesNotMatch(html,/Material\+Symbols|material-symbols-outlined|Fraunces|Plus\+Jakarta|Plus Jakarta/i);
  assert.match(html,/writing-lab-portal\.css/);
  assert.doesNotMatch(html,/<script[^>]+writing-lab-client\.js/,'Writing Lab stays off the initial dashboard load');
  assert.match(portal,/ensureWritingLabRuntimeLoaded/);
  assert.match(portal,/\/writing-lab-client\.js\?v=[^\s\x27"]+/);
  assert.doesNotMatch(lab,/<h1\b/,'Writing Lab uses the application page title instead of nested H1s');
  assert.doesNotMatch(portal,/<h1 class="essay-title">/,'Essay preview must not add a second application H1');
  assert.match(portal,/function renderVocabFlashcardContainer\(\)/,'use the existing vocabulary flashcard flow');
  assert.match(portal,/function toggleFlashcardFlip\(\)/,'preserve the existing flashcard flip state');
  assert.match(portal,/function handleFlashcardAction\(gotIt\)/,'preserve saved vocabulary review actions');
  for(const [id,label] of [['f_intro','Introduction'],['f_bp1','Body paragraph 1'],['f_bp2','Body paragraph 2'],['f_concl','Conclusion']]) {
    assert.match(html,new RegExp('id="'+id+'"[^>]*aria-label="'+label+'"'));
  }
  assert.match(html,/<button[^>]+practice-shortcut-link[^>]*>Practise this question/);
  assert.match(html,/My Next Steps/);
  assert(html.indexOf('id="portalResume"') < html.indexOf('id="nextStepsDashboardCard"'));
  assert(html.indexOf('id="nextStepsDashboardCard"') < html.indexOf('id="todayPlanCard"'));
  assert.match(html,/index\.min\.js/);
  assert(html.indexOf('auth-boot.js')<html.indexOf('index.min.js'));
  assert.match(html,/\/ipt-tokens\.css/);
  assert.match(html,/\/portal-liquid-glass\.css/);
  assert.match(html,/\/portal-home-practice\.css/);
  assert.doesNotMatch(html,/<link[^>]+portal-insights\.css/,'Insights CSS stays off the first-load path');
  assert.doesNotMatch(html,/<link[^>]+portal-vocab-library\.css/,'Vocabulary and Library CSS stays off the first-load path');
  assert.doesNotMatch(html,/<link[^>]+portal-writing-motion\.css/,'Writing motion CSS stays off the first-load path');
  assert.match(html,/\/portal-writing-motion\.js\?v=20260929-native-cursor/);
  assert.match(html,/\/portal-shell\.js\?v=[^"\s]+/);
  assert.match(html,/\/portal-liquid-glass\.css\?v=20260928-layoutfix-final/);
  assert(html.indexOf('/interventions.css') < html.indexOf('/ipt-tokens.css'),'IPT tokens load after legacy feature styles');
  assert(html.indexOf('/ipt-tokens.css') < html.indexOf('/portal-liquid-glass.css'),'Liquid Glass loads after tokens');
  assert(html.indexOf('/portal-liquid-glass.css') < html.indexOf('/portal-home-practice.css'),'Home and Practice styles load after the shell');
  assert.doesNotMatch(html,/data:image\//i,'production HTML must not embed a Base64 logo');

  for(const [name,source] of [['portal',portal],['reading',reading],['writing lab',lab]]){
    assert.doesNotMatch(source,/\bprompt\s*\(/,name+' must not use prompt()');
    assert.doesNotMatch(source,/\bconfirm\s*\(/,name+' must not use confirm()');
    assert.doesNotMatch(source,/font-size:\s*(?:[0-9]|1[01](?:\.\d+)?)px/,name+' generated UI must not use sub-12px text');
    assert.doesNotMatch(source,/#4f46e5|#5a51da|#6366f1|rgba\(99,\s*102,\s*241/i,name+' must not reintroduce the legacy indigo palette');
  }

  for(const [name,source] of [['index.css',css],['portal-workspace.css',workspaceCss],['ipt-tokens.css',tokensCss],['portal-liquid-glass.css',liquidCss],['portal-home-practice.css',homePracticeCss],['portal-insights.css',insightsCss],['portal-vocab-library.css',vocabLibraryCss],['portal-writing-motion.css',writingMotionCss]]){
    const sizes=[...source.matchAll(/@media\s*\((?:max|min)-width:\s*([0-9.]+)px\)/g)].map(m=>Number(m[1]));
    assert(sizes.every(n=>[640,900,1200].includes(n)),name+' uses only the three portal breakpoints');
    assert.doesNotMatch(source,/font-size:\s*(?:[0-9]|1[01](?:\.\d+)?)px/,name+' must not use sub-12px text');
    assert.doesNotMatch(source,/#4f46e5|#5a51da|#6366f1|rgba\(99,\s*102,\s*241/i,name+' must not reintroduce the legacy indigo palette');
  }

  assert.match(css,/--ink-mute:\s*#526174/);
  assert.match(css,/min-height:44px/);
  assert.match(tokensCss,/--ipt-blue-700:\s*#205080/);
  assert.match(tokensCss,/--ipt-red-600:\s*#c53030/i);
  assert.match(liquidCss,/backdrop-filter:\s*blur\(22px\)/);
  assert.match(liquidCss,/@media\s*\(prefers-reduced-motion:\s*reduce\)/);
  assert.match(liquidCss,/@media \(max-width: 640px\)[\s\S]*?\.app-shell\s*\{[\s\S]*?grid-template-columns:\s*minmax\(0,\s*1fr\)/,'mobile Liquid Glass shell collapses to one column');
  assert.match(liquidCss,/#portalSidebar \.nav-group-label\s*\{[^}]*font-size:\s*12px/,'sidebar group labels stay at or above 12px');
  assert.match(liquidCss,/@media \(max-width: 640px\)[\s\S]*?#portalSidebar\s*\{[^}]*position:\s*fixed/,'mobile sidebar remains fixed off-canvas');
  assert.match(workspaceCss,/#portalSidebar \.nav-group-secondary:not\(:has\(\.nav-item\)\) \{ display: none; \}/,'removed admin navigation must not leave an empty sidebar separator');
  assert.match(liquidCss,/#portalSidebar\s*\{\s*overflow-y:\s*auto;/,'short viewports must keep sidebar navigation scrollable');
  assert.match(liquidCss,/\.modal\s*\{\s*overflow-y:\s*auto;/,'glass modals must keep their vertical scroll');
  assert.match(liquidCss,/\.topbar\s*\{\s*overflow:\s*hidden;\s*height:\s*auto;/,'glass topbar must grow instead of clipping wrapped controls');
  assert.match(liquidCss,/@media\s*\(max-width:\s*900px\)[\s\S]*?\.topbar\s*\{[^}]*flex-wrap:\s*wrap\b/,'tablet topbar must wrap instead of clipping controls');
  assert.match(liquidCss,/transform:\s*translateX\(calc\(-100% - 16px\)\)/,'closed mobile drawer must clear its glass margin completely');
  assert.match(vocabLibraryCss,/#libraryPane \.layout\s*\{\s*height:\s*100% !important;\s*min-height:\s*0;/,'library layout must follow the remaining portal canvas height');
  assert.match(vocabLibraryCss,/grid-template-columns:\s*clamp\(220px,18vw,258px\) minmax\(0,1\.12fr\) minmax\(300px,\.92fr\)/,'library columns must shrink without horizontal overflow');
  assert.match(vocabLibraryCss,/@media\s*\(max-width:\s*1200px\)[\s\S]*?#libraryPane \.layout\s*\{\s*flex:\s*1;\s*height:\s*auto !important;\s*min-height:\s*0;/,'responsive library toolbar must not add height on top of a full-height workspace');
  assert.match(vocabLibraryCss,/\.flashcard-back\s*\{\s*overflow-y:\s*auto;[\s\S]*?justify-content:\s*flex-start !important;/,'long flashcard backs must scroll from the top');
  assert.match(homePracticeCss,/@media \(max-width: 640px\)[\s\S]*?#dashboardPane \.challenge-word-box\{[^}]*flex-direction:column/,'Home challenge controls stack on mobile');
  assert.match(homePracticeCss,/#dashboardPane \.vocab-try-row\{[^}]*flex-direction:column/,'Home vocabulary input stacks on mobile');
  assert.match(portalShell,/portal-writing-motion\.css\?v=20260929-native-cursor/);
  assert.match(portalShell,/new Set\(\['practice', 'swt'\]\)/,'Writing presentation is restricted to Essay and SWT routes');
  assert.match(writingMotion,/new Set\(\['practice', 'swt'\]\)/);
  assert.match(writingMotion,/prefers-reduced-motion: reduce/);
  assert.doesNotMatch(writingMotion,/pointermove|clientX|clientY|ipt-writing-cursor/,'Writing motion must not track the pointer or replace the native cursor');
  assert.doesNotMatch(writingMotion,/speakingPane|speaking-[a-z]+/i,'Writing motion helper must not target Speaking');
  assert.doesNotMatch(writingMotionCss,/#speakingPane|data-section="speaking/i,'Writing motion CSS must not target Speaking routes');
  assert.match(portalShell,/MutationObserver/);
  assert.match(portalShell,/ipt-nav-indicator/);
  assert.match(portalShell,/iptShellReady/);
  assert.match(portalShell,/portal-insights\.css\?v=20260929-assistant-ux2/);
  assert.match(portalShell,/portal-vocab-library\.css\?v=20260928-layoutfix-final/);
  assert.match(portalShell,/addEventListener\('error', \(\) => link\.remove\(\), \{ once: true \}\)/,'failed lazy presentation styles must be retryable');
  assert.match(portalShell,/new Set\(\['mock-tests', 'writing-mocks', 'next-steps', 'progress'\]\)/);
  assert.match(portalShell,/new Set\(\['vocab', 'library'\]\)/);
  assert.match(html,/\/personal-ai-assistant\.js\?v=\d+/);
  assert.doesNotMatch(html,/<script[^>]+interventions-client\.js/,'Next Steps stays off the initial dashboard load');
  assert.match(portal,/ensureInterventionsRuntimeLoaded/);
  assert.match(portal,/\/interventions-client\.js\?v=\d+/);
  assert.doesNotMatch(html,/<script[^>]+student-progress\.js/,'Progress stays off the initial dashboard load');
  assert.match(portal,/ensureStudentProgressRuntimeLoaded/);
  assert.match(personalAssistant,/\/api\/interventions\/screen-help/,'assistant should answer from the current portal screen');
  assert.match(personalAssistant,/function screenContext\(usePage = true\)/,'assistant should collect current visible page context');
  assert.match(personalAssistant,/aria-label="Open AI Assistant" title="Open AI Assistant"/,'assistant mascot should open the current-page side panel');
  assert.match(personalAssistant,/class="personal-ai-close-button"[^>]*data-ai-close[^>]*aria-label="Close AI Assistant"/,'assistant panel should expose a clear labelled close button');
  assert.match(personalAssistant,/event\.key === 'Escape'.*closePanel\(\)/s,'Escape key should continue to close the assistant');
  assert.doesNotMatch(personalAssistant,/Coming Soon/,'assistant must not show a Coming Soon state');
  assert.doesNotMatch(personalAssistantCss,/Coming Soon/,'assistant presentation must not contain Coming Soon copy');
  assert.match(personalAssistant,/Reading this page/,'assistant should disclose current-page context use');
  assert.match(personalAssistant,/Student-selected text/,'assistant should prioritise selected page text');
  assert.match(personalAssistant,/Use page context/,'students should control page-context sharing');
  assert.match(personalAssistant,/function screenIdentity\(\)/,'assistant should identify the current visible screen separately from chat history');
  assert.match(personalAssistant,/refreshScreenContext\(\)/,'assistant should refresh its context before every question');
  assert.match(personalAssistant,/requestVersion !== contextVersion \|\| requestKey !== activeContextKey/,'assistant should ignore a reply generated for an older screen');
  assert.match(personalAssistant,/requestController\.abort\(\)/,'assistant should cancel an in-flight reply when the screen changes');
  assert.match(personalAssistant,/messages = \[\];/,'assistant should isolate chat history by visible screen');
  assert.match(interventionsClient,/function inferHelpTask\(message\)/,'assistant should infer explicit task names from student messages');
  assert.match(interventionsClient,/repeat\\s\+sentences\?/,'Repeat Sentence mismatch should be detectable');
  assert.match(interventionsClient,/Task auto-detect is on/,'student should understand that task mismatch is handled');
  assert.match(interventionsClient,/Recommended next step/,'assistant should turn advice into a clear action');
  assert.match(interventionsClient,/formatCoachText/,'assistant replies should render readable structured text instead of raw markdown markers');
  assert.match(interventionsClient,/ensureAssistantPresentation/,'assistant must load its presentation layer even when the cached shell is stale');
  assert.match(interventionsClient,/portal-insights\.css\?v=20260929-assistant-ux2/,'assistant fallback stylesheet should use the current cache-busted asset');
  assert.match(interventionsClient,/open the floating AI Assistant/i,'My Next Steps should point to the single floating assistant');
  assert.doesNotMatch(interventionsClient,/\+helpPanel\(\)\s*\n\s*\+\(completed\.length/,'My Next Steps must not render a duplicate assistant chat');
  assert(portalShell.indexOf("key: 'insights'") < portalShell.indexOf("key: 'vocab-library'"),'lazy stylesheet priority stays deterministic');
  assert(Buffer.byteLength(tokensCss)+Buffer.byteLength(liquidCss)+Buffer.byteLength(homePracticeCss) <= 29916,'first-load Liquid Glass presentation CSS stays within the 10% growth cap');
  assert.doesNotMatch(portalShell,/\bprompt\s*\(|\bconfirm\s*\(/);
  const catalogue=read('public/practice-catalogue.js');
  assert.doesNotMatch(catalogue,/Tests per page/);
  assert.match(catalogue,/Integrated Reading & Listening Sectional Mock/);
  assert.match(catalogue,/Reading Practice Mock/);
  assert.match(catalogue,/Array\.from\(\{ length: 15 \}/);
  assert.match(catalogue,/minutes: 23/);
  assert.doesNotMatch(catalogue,/mock-catalogue-description/);
  assert.doesNotMatch(catalogue,/mock-catalogue-scope/);
  assert.doesNotMatch(catalogue,/Includes:/);
  assert.match(catalogue,/Last attempt/);
  assert.match(catalogue,/In progress/);
  assert.match(server,/max-age=31536000, immutable/);
  assert.match(build,/terser@5\.44\.0/);
  assert.match(build,/ipt-brisbane-logo\.webp/);
  assert.match(build,/ffmpeg/);
});
