'use strict';
// Original teaching material; not recalled or licensed Pearson examination items.
const types = {
  ra: { name: 'Read Aloud', preparation: 35, seconds: 40, instruction: 'Read the passage aloud exactly as written. Use the preparation time to notice punctuation and meaningful phrases.' },
  rs: { name: 'Repeat Sentence', preparation: 0, seconds: 15, instruction: 'Listen once, then repeat the sentence exactly. Keep the words in their original order.' },
  di: { name: 'Describe Image', preparation: 25, seconds: 40, instruction: 'Describe the image in your own words. Identify its topic, main features and important relationships, using accurate details.' },
  rl: { name: 'Retell Lecture', preparation: 10, seconds: 40, instruction: 'Listen to the lecture, then retell its main ideas and relevant supporting details in your own words.' },
  sgd: { name: 'Summarise Group Discussion', preparation: 10, seconds: 120, instruction: 'Listen to three speakers. Summarise the topic, each person’s contribution, and how their views relate to one another.' },
  rts: { name: 'Respond to a Situation', preparation: 10, seconds: 40, instruction: 'Read and listen to the situation. Speak directly to the person indicated, using an appropriate tone and meeting the communication goal.' }
};
const questions = [];
function add(type, rows) { rows.forEach((q, i) => questions.push({ id: type + '-' + (i + 1), type, ...types[type], ...q })); }
add('ra', [
  { title: 'Urban green spaces', text: 'Urban parks provide more than attractive places to relax. Trees offer shade, absorb rainwater and create habitats for wildlife. However, these benefits depend on thoughtful planning and regular maintenance. By choosing suitable plants and involving local residents, cities can develop green spaces that remain useful and welcoming throughout the year.' },
  { title: 'Learning through retrieval', text: 'Students often review familiar notes because the material feels easy to recognise. Yet recognition is not the same as remembering information independently. Brief practice tests encourage learners to retrieve ideas from memory. When followed by useful feedback, this approach can reveal gaps in understanding and support more effective revision.' },
  { title: 'Preserving digital records', text: 'Digital collections allow researchers to consult historical documents without travelling to an archive. Nevertheless, scanning a document is only the beginning of preservation. Files need accurate descriptions, reliable storage and regular checks. As technology changes, institutions must also update older formats so that valuable information remains accessible to future readers.' },
  { title: 'Public transport connections', text: 'A convenient public transport network depends on connections as well as frequent services. Passengers need clear information and enough time to transfer between routes. When buses and trains follow coordinated schedules, journeys become more predictable. This reliability can make public transport a practical choice for people with different daily routines.' },
  { title: 'Citizen science', text: 'Citizen science projects invite members of the public to contribute observations to research. Volunteers may record bird sightings or measure local rainfall using shared methods. Training and careful data checks help improve reliability. In return, participants gain a better understanding of scientific questions and the environments in which they live.' }
]);
add('rs', [
  { title: 'Library opening hours', text: 'The university library will remain open until midnight during the examination period.' },
  { title: 'Preparing for the seminar', text: 'Please read the first two chapters before attending the seminar on Thursday.' },
  { title: 'Research evidence', text: 'Reliable research requires clear questions and evidence from a range of sources.' },
  { title: 'A room change', text: 'Tomorrow’s lecture has been moved to the larger room beside the main entrance.' },
  { title: 'Submitting a group report', text: 'Each group must submit one report and include the names of all members.' }
]);
add('di', [
  { title: 'Household electricity use', visual: { kind: 'bar', title: 'Household electricity use', subtitle: 'Share of annual consumption (%)', labels: ['Heating', 'Cooling', 'Appliances', 'Lighting'], values: [40, 25, 20, 15] },
    facts: ['The chart compares four uses of household electricity.', 'Heating is highest at 40%.', 'Cooling is 25%, appliances 20% and lighting 15%.', 'Heating and cooling together account for 65%, almost two thirds of use.'],
    sample: 'The given image provides the detailed information about household electricity use. Overall, heating accounts for the largest share at 40 percent, followed by cooling at 25 percent and appliances at 20 percent. Lighting has the smallest proportion, at 15 percent. Together, heating and cooling make up 65 percent of consumption, so controlling indoor temperature uses almost two thirds of the household’s electricity.' },
  { title: 'A student’s monthly budget', visual: { kind: 'pie', title: 'A student’s monthly budget', subtitle: 'Share of monthly spending (%)', labels: ['Rent', 'Food', 'Transport', 'Study materials', 'Leisure'], values: [40, 25, 15, 12, 8] },
    facts: ['The pie chart shows five categories of a student’s monthly spending.', 'Rent is the largest category at 40%, followed by food at 25% and transport at 15%.', 'Study materials represent 12% and leisure 8%.', 'Rent and food together account for 65% of the budget.'],
    sample: 'The given image provides the detailed information about a student’s monthly budget. Rent is the largest expense at 40 percent, followed by food at 25 percent and transport at 15 percent. The remaining categories are study materials at 12 percent and leisure at 8 percent. Overall, rent and food together account for 65 percent of spending, while leisure is the smallest expense.' },
  { title: 'Bicycle trips to campus', visual: { kind: 'line', title: 'Bicycle trips to campus', subtitle: 'Average trips per weekday', labels: ['2019', '2020', '2021', '2022', '2023'], values: [200, 280, 250, 360, 450] },
    facts: ['The line graph shows average weekday bicycle trips to campus from 2019 to 2023.', 'Trips rose from 200 in 2019 to 280 in 2020.', 'There was a temporary fall to 250 in 2021.', 'Trips then increased to 360 in 2022 and peaked at 450 in 2023.', 'The final value is more than twice the initial value.'],
    sample: 'The given image provides the detailed information about bicycle trips to campus between 2019 and 2023. Overall, the number of trips increased substantially, from 200 to 450 per weekday. It first rose to 280 in 2020, then fell slightly to 250 in 2021. After that, it climbed to 360 in 2022 and reached its highest point in 2023, more than double the starting figure.' },
  { title: 'Getting to campus', visual: { kind: 'table', title: 'Getting to campus', subtitle: 'Students surveyed at two campuses', columns: ['Transport', 'North', 'South'], rows: [['Bus', '180', '140'], ['Train', '120', '160'], ['Bicycle', '60', '80'], ['Walk', '40', '20']] },
    facts: ['The table compares four travel methods at North and South campuses.', 'Both campuses have 400 surveyed students.', 'Bus travel is highest at North with 180 students; train travel is highest at South with 160.', 'Cycling is more common at South, 80 versus 60.', 'Walking is least common at both campuses, 40 at North and 20 at South.'],
    sample: 'The given image provides the detailed information about how students travel to two campuses. Both campuses have 400 students in the survey. Buses are most popular at North, with 180 users, while trains lead at South with 160. South also has more cyclists, at 80 compared with 60. Walking is the least common method at both campuses, with 40 students at North and 20 at South.' },
  { title: 'Collecting rainwater', visual: { kind: 'process', title: 'Collecting rainwater for a garden', subtitle: 'A simple five-stage system', steps: ['Rain falls on roof', 'Gutters collect runoff', 'Filter removes debris', 'Tank stores water', 'Pump supplies garden'] },
    facts: ['The diagram explains a five-stage process for collecting rainwater for garden use.', 'Rain falls on a roof and gutters collect the runoff.', 'A filter removes debris before water enters a storage tank.', 'A pump moves stored water to the garden.', 'The diagram does not show treatment that makes the water safe to drink.'],
    sample: 'The given image provides the detailed information about collecting rainwater for a garden. The process begins when rain falls on a roof. Gutters collect the runoff and direct it through a filter, which removes debris. The filtered water then enters a storage tank. Finally, a pump supplies the garden. Overall, the system collects, filters, stores and reuses rainwater; it does not show a drinking-water treatment process.' }
]);
add('rl', [
  { title: 'Why urban trees need planning', text: 'Today I want to explain why planting more trees is not, by itself, a complete urban cooling strategy. Trees can reduce heat in two ways. Their leaves shade surfaces such as pavements, and water released through those leaves cools the surrounding air. However, a newly planted tree provides much less shade than a mature tree, so protecting existing trees is important. Location also matters. Planting beside a busy walking route may benefit more people than planting in an area that is rarely used. Species should be chosen for local conditions, including the amount of water available and the space for roots. If roots are restricted or watering stops too soon, young trees may fail to survive. Finally, urban forestry is a long-term commitment. Councils need funds for maintenance, not just for the initial planting campaign. The main lesson is that successful cooling depends on keeping suitable trees healthy in places where their shade is genuinely useful.',
    facts: ['Trees cool through shade and water released from leaves.', 'Mature trees should be protected because new trees offer less shade.', 'Locations and species must suit people’s needs and local growing conditions.', 'Root space, watering and ongoing maintenance are essential for survival.', 'The conclusion is that effective cooling requires long-term planning, not simply more planting.'],
    sample: 'The lecture explains that urban cooling requires more than planting additional trees. Trees provide shade and release water through their leaves, but mature trees offer greater immediate benefits. The speaker emphasises choosing suitable species and useful locations, while allowing sufficient root space and watering. Councils also need long-term maintenance funding. Overall, healthy, well-placed trees are more valuable than a planting campaign without continuing care.' },
  { title: 'Testing as a learning activity', text: 'Many people think that a test only measures what a student has already learned. In fact, a short practice test can also be a learning activity. When students try to recall an idea without looking at their notes, they practise retrieving it from memory. This effort can make later recall easier. Simply rereading a familiar page may create confidence, but that confidence does not always reflect an ability to explain the material independently. Practice questions can reveal the difference. Feedback remains essential, because students need to identify and correct mistakes rather than repeatedly rehearse them. Timing matters too. Several short sessions spread across a week are generally more useful than one long session immediately before an examination. Practice testing should also include explanations and applications, not just isolated facts. A student who can connect an idea to a new example is demonstrating deeper understanding. The purpose, then, is not to increase pressure through constant formal examinations. It is to use manageable retrieval activities, followed by feedback, to guide effective learning.',
    facts: ['Practice tests can support learning as well as measure it.', 'Retrieving ideas independently develops recall and reveals gaps that rereading may hide.', 'Feedback is needed to correct mistakes.', 'Practice should be spaced and include explanation or application.', 'The aim is useful low-pressure learning, not more formal examinations.'],
    sample: 'The lecture describes practice testing as a learning tool, not just a way to measure achievement. Recalling ideas independently strengthens retrieval and exposes gaps that rereading may conceal. However, students need feedback to correct errors. The speaker also recommends short, spaced sessions and questions that require explanation or application. The overall aim is manageable, meaningful practice rather than increasing pressure through frequent formal examinations.' },
  { title: 'Digital access to museum collections', text: 'Museums increasingly make their collections available online, but digital access is not simply a matter of uploading photographs. A useful digital record needs context. Visitors may need to know where an object was made, how it was used and why different communities value it. Accurate descriptions make collections searchable and help prevent misleading interpretations. Online access can benefit people who live far from a museum or cannot enter the building easily. It can also support teachers who want to compare objects from several institutions. Nevertheless, a photograph cannot reproduce every aspect of a physical object. Its scale, texture and surrounding exhibition may be difficult to convey. Digital projects also require continuing maintenance. Websites, file formats and accessibility requirements change, so institutions must budget for future updates. The strongest approach treats digital collections as a complement to physical visits, not a complete replacement. Technology is most useful when it broadens access while preserving the context that gives an object meaning.',
    facts: ['Digital museum records need reliable context, not photographs alone.', 'Descriptions explain origins, uses and significance and support searching.', 'Online collections improve access and help teaching.', 'Digital images cannot fully convey physical scale, texture or exhibition context.', 'Ongoing updates are needed, and digital access complements physical visits.'],
    sample: 'The speaker argues that effective digital museum collections need accurate context as well as photographs. Descriptions help people understand an object’s origin and significance, while online access benefits distant visitors and teachers. However, images cannot fully reproduce physical qualities such as scale and texture. Digital collections also need continuing updates. They therefore work best as a complement to physical visits, broadening access without losing meaning.' },
  { title: 'Reducing food waste on campus', text: 'A university cafeteria that wants to reduce food waste should first find out where the waste occurs. Food discarded during preparation requires a different response from food left on customers’ plates. For example, better forecasting may prevent the kitchen from preparing too many portions, while allowing customers to choose a smaller serving may reduce plate waste. Staff should measure waste over several ordinary weeks rather than draw conclusions from one unusually busy day. The results can guide a small trial, such as changing portion sizes at one counter. Importantly, reducing waste does not mean ignoring food safety. Surplus food can only be redistributed when storage, handling and collection meet the relevant requirements. Communication also matters: customers may accept changes more readily if they understand the reasons and retain a choice of portions. Finally, the cafeteria should measure waste again after the trial. A successful programme uses evidence, tests practical changes and checks whether those changes actually produce a lasting improvement.',
    facts: ['Measure where and how much food is wasted before intervening.', 'Forecasting reduces overproduction; portion choices can reduce plate waste.', 'Collect representative data and trial a targeted change.', 'Redistribution must still satisfy food-safety requirements.', 'Explain changes and measure outcomes again to check lasting improvement.'],
    sample: 'The lecture recommends an evidence-based approach to reducing cafeteria food waste. Staff should distinguish preparation waste from plate waste and collect data over several weeks. Better forecasting can reduce overproduction, while smaller serving options may help customers waste less. Any redistribution must remain safe. The speaker concludes that targeted trials, clear communication and follow-up measurements are needed to identify changes that work over time.' },
  { title: 'Making online surveys more representative', text: 'An online survey can collect responses quickly, but a large number of answers does not automatically make the results representative. The people who notice a survey and choose to complete it may differ from those who do not participate. For instance, a questionnaire shared only through a student society may mainly reach members of that society. Researchers should therefore define the population they want to understand before deciding how to recruit respondents. Clear, neutral questions are also important. A question that assumes a service is excellent may encourage favourable answers and obscure genuine concerns. Short pilot studies can reveal confusing wording or missing response options. During analysis, researchers should examine which groups are underrepresented and explain the limitations openly. They should not claim that a convenient sample speaks for everyone. Good survey practice combines thoughtful recruitment, careful question design and honest interpretation. Speed and convenience are useful, but they cannot replace attention to the quality of the evidence.',
    facts: ['A large online sample is not automatically representative.', 'Self-selection and narrow recruitment can exclude important groups.', 'Define the intended population and use clear, neutral questions.', 'Pilot testing can identify confusing wording and missing options.', 'Analyse underrepresentation and report limitations honestly.'],
    sample: 'The lecture explains that online surveys are not necessarily representative, even when many people respond. Self-selection and limited recruitment can bias the sample. Researchers should identify their target population, use neutral questions and pilot the questionnaire. They must also check which groups are underrepresented and acknowledge limitations. Overall, reliable evidence depends on good design and honest interpretation, not simply fast data collection.' }
]);
add('sgd', [
  { title: 'Extending library opening hours', turns: [
    ['Maya', 'I think the library should stay open later throughout the semester, not only during exams. Some students work in the evening and need somewhere quiet afterwards. My shared house is noisy, so having access until midnight would make a real difference. What do you both think?'],
    ['Ben', 'I understand the need, but opening the whole building could be expensive. We would need security, lighting and staff even if only a few students came. I would rather see a limited late-opening area, with student-card access, than promise a service the library cannot sustain.'],
    ['Clara', 'A small area sounds sensible, but getting home safely is another issue. The last bus leaves before midnight. Students without cars might not benefit unless transport is considered too. Perhaps the university could coordinate a shuttle on the busiest nights rather than run it every evening.'],
    ['Maya', 'That is a fair point. I do not need the borrowing desk to stay open; I mainly need a desk, power and internet. We could start with the ground-floor study room. A short survey might tell us which nights working students actually need it most.'],
    ['Ben', 'I would support a trial based on that survey. We could count visits and check the cost for six weeks, then decide whether to continue. Clear rules would matter, especially about noise, visitors and what students should do if they need help after staff leave.'],
    ['Clara', 'Then our recommendation could combine a small supervised study area with a transport check. We should ask students about both demand and travel, and make sure accessibility is included. That gives the university evidence before it commits to opening the entire library later.'] ],
    facts: ['The discussion concerns later library access for students.', 'Maya supports later opening because work and noisy housing limit study opportunities.', 'Ben worries about cost and proposes a small card-access area with rules and a six-week trial.', 'Clara raises safe transport and accessibility, suggesting a shuttle on busy nights.', 'The group converges on surveying demand and trialling a limited study area alongside transport planning.'],
    sample: 'The three students discuss extending library opening hours. Maya supports later access because students with jobs or noisy accommodation need a quiet place to study. Ben agrees there may be demand, but questions the cost of keeping the whole building open. He suggests a smaller area with controlled access, clear rules and a six-week trial. Clara adds that safe travel is equally important, since the last bus leaves before midnight, and proposes checking shuttle options and accessibility. Maya accepts the smaller-area idea because she mainly needs a desk and internet, not a borrowing service. The discussion therefore moves from a general request for longer hours towards a more practical proposal: survey students, trial a limited study space and consider transport before expanding the service.' },
  { title: 'Choosing a group-project format', turns: [
    ['Daniel', 'For our environmental project, I would like to make a short video instead of a slide presentation. We could show the recycling facilities around campus and interview students. That might make our findings easier to understand than reading statistics from a screen during the final class.'],
    ['Leah', 'A video could be engaging, but editing takes time and none of us has much experience. We also have to show how we collected and analysed our data. I worry that production work might distract us from the research, which is the main part of the assessment.'],
    ['Omar', 'Could we combine the approaches? A few short clips could introduce the problem, followed by slides explaining the evidence. We should also provide captions and avoid filming anyone without permission. The format should help communicate the findings rather than become the main focus of the project.'],
    ['Daniel', 'I like that compromise. We could record the facilities without identifying students, and use an anonymous questionnaire instead of interviews. I can take responsibility for two brief clips. If the clips do not work well, the research presentation would still be complete without them.'],
    ['Leah', 'That makes the workload more manageable. Let us agree on the research questions and divide the analysis first. Then we can set a strict time limit for filming and editing. I would also like us to practise together so the final presentation feels like one coherent explanation.'],
    ['Omar', 'Agreed. We should check the assessment instructions before committing, share a draft early and keep the clips short and accessible. The final plan is a slide-based presentation supported by video, with research quality, consent and clear teamwork taking priority over elaborate production.'] ],
    facts: ['The students are deciding how to present an environmental group project.', 'Daniel initially favours a video showing campus recycling and interviews.', 'Leah worries editing will distract from research and exceed their skills or time.', 'Omar proposes short clips plus evidence-focused slides, with captions and consent.', 'They agree on a mainly slide-based presentation, limited filming, clear responsibilities and joint rehearsal.'],
    sample: 'The group discusses the best format for an environmental project. Daniel initially favours a video because footage of campus recycling could make the findings engaging. Leah is concerned that filming and editing would consume time needed for research and analysis. Omar proposes a compromise: use a few short clips to introduce the issue, then present the evidence through slides. He also highlights captions and permission when filming. Daniel accepts the compromise and offers to produce brief clips without identifying students. Leah then recommends agreeing on research questions, dividing the analysis and rehearsing together. Overall, they choose a research-led slide presentation with limited video support, balancing engagement with workload, accessibility and ethical responsibilities.' },
  { title: 'Improving campus food choices', turns: [
    ['Aisha', 'I would like the cafeteria to offer more affordable plant-based meals. There is usually one option, but it is often the same dish. Students with different diets should have a genuine choice, and some of my friends bring lunch because the available meals are too expensive.'],
    ['Tom', 'More choice sounds good, but the kitchen already throws away food when demand is low. Adding several dishes every day could make that worse. I think the cafeteria should first find out what students would actually buy and whether it can use ingredients across different meals.'],
    ['Sophie', 'Price and information matter too. A meal may look suitable but contain an ingredient someone cannot eat. Clear labels would help. We could ask for one rotating, reasonably priced dish each day and make sure staff can answer questions, instead of expanding the whole menu at once.'],
    ['Aisha', 'A rotating dish would be a useful start, especially if students could suggest recipes. I do not expect every meal to suit everyone. I mainly want variety across the week and a price that makes buying lunch realistic for students who are watching their budgets.'],
    ['Tom', 'Then we should propose a trial rather than a permanent change immediately. The kitchen could record sales and leftovers for a month. If the new option sells well without increasing waste, that would provide evidence for expanding it or adjusting the portion sizes later.'],
    ['Sophie', 'Let us include a simple feedback form and accurate ingredient labels in the trial. Students could comment on taste, value and portion size. We seem to agree that affordable variety is the goal, but it should be introduced gradually and checked against actual demand.'] ],
    facts: ['The group wants better campus food choices.', 'Aisha asks for varied, affordable plant-based meals.', 'Tom warns that adding dishes without demand data could increase waste.', 'Sophie emphasises ingredient information and one rotating affordable option.', 'They support a month-long trial using sales, leftovers and student feedback to guide changes.'],
    sample: 'The students discuss improving food choices in the campus cafeteria. Aisha wants more varied and affordable plant-based meals, explaining that limited options and high prices discourage some students from buying lunch. Tom supports choice but worries that a larger menu could increase food waste if demand is uncertain. Sophie adds the need for clear ingredient labels and suggests one reasonably priced rotating dish rather than a major expansion. Aisha accepts this gradual approach, while Tom recommends measuring sales and leftovers during a month-long trial. Sophie proposes collecting feedback on taste, value and portion size. Their shared position is to improve affordable variety through a small, clearly labelled trial and use evidence before making wider changes.' },
  { title: 'Making lecture recordings useful', turns: [
    ['Ethan', 'I find lecture recordings very helpful because I can revisit difficult explanations and pause to check my notes. They are also useful if someone misses class for a legitimate reason. I think every lecture should be recorded and made available soon after the class finishes.'],
    ['Nina', 'I use them too, but I sometimes postpone watching because I know the recording will be there. Then several lectures pile up before a test. Recordings are useful resources, but simply providing them does not mean students will use them effectively or keep up with the course.'],
    ['Luis', 'Perhaps the course could provide short guides alongside each recording. Time markers for key topics would make revision easier, and a few practice questions could encourage students to check their understanding. Captions are important as well, but they should be checked because technical terms are sometimes transcribed incorrectly.'],
    ['Ethan', 'Those additions would definitely help. I still think recordings should remain available for revision rather than disappear after a few days. Some topics make more sense later in the semester. We should encourage attendance without removing a resource that students use in different ways.'],
    ['Nina', 'I agree about keeping access. My concern is study habits, not restricting recordings. A weekly reminder and a short self-check could help me stay on schedule. It would also be useful if teachers explained when to review a short section instead of replaying an entire lecture.'],
    ['Luis', 'So we could recommend continued access, accurate captions, topic markers and optional self-checks. Live classes still offer questions and discussion, while recordings support review. The two should complement each other, with some guidance to help students avoid leaving all their viewing until the last minute.'] ],
    facts: ['The discussion concerns effective use of lecture recordings.', 'Ethan values replaying difficult explanations and wants continued access.', 'Nina warns recordings can encourage postponement and accumulated work.', 'Luis proposes topic markers, checked captions and practice questions.', 'They agree recordings should complement attendance and include guidance and self-checks rather than restricted access.'],
    sample: 'The discussion focuses on making lecture recordings more useful. Ethan values being able to replay difficult material and argues that recordings should remain available for later revision. Nina agrees they are helpful but describes how easy it is to postpone watching and fall behind. Luis suggests topic markers, accurate captions and practice questions to support purposeful review. Ethan supports these improvements but opposes removing recordings after a short period. Nina clarifies that her concern is study habits, and proposes reminders and guidance on reviewing selected sections. The group ultimately agrees on continued access supported by accessible recordings and self-checks. They see recordings as a complement to live participation, not a replacement for attendance or a reason to delay study.' },
  { title: 'Planning a community volunteering day', turns: [
    ['Grace', 'For our student society’s volunteering day, I suggest helping at the community garden. We could do something practical outdoors and meet local residents. A full Saturday would allow us to finish a useful amount of work rather than spend most of a short visit getting organised.'],
    ['Sam', 'I like the garden idea, but a full day may exclude students who have weekend jobs or caring responsibilities. We also should not assume that everyone can do heavy outdoor work. I would prefer flexible shifts and a choice of activities so more people can take part.'],
    ['Priya', 'Before planning the timetable, we should ask the garden organisers what help they actually need. They may need seed sorting, signs or publicity as well as planting. A project is more useful when it supports the community’s priorities rather than just offering us an enjoyable day out.'],
    ['Grace', 'That is a good reminder. I can contact the coordinator and ask about suitable jobs and the number of volunteers they can manage. Perhaps we could offer a morning and an afternoon shift, with some lighter tasks available under cover if the weather is poor.'],
    ['Sam', 'Two shifts would work better for me. We should also explain transport options and any equipment people need. Students could choose activities when signing up, but we should avoid promising a particular task until the coordinator confirms that it is useful and safe.'],
    ['Priya', 'Exactly. Once the coordinator responds, we can publish an accessible plan and arrange a short briefing. Afterwards, we should ask the garden whether our contribution was helpful. We agree on volunteering there, provided the event is flexible, well organised and shaped by the garden’s needs.'] ],
    facts: ['The students plan a volunteering day at a community garden.', 'Grace favours practical work and initially suggests a full Saturday.', 'Sam raises time constraints and physical accessibility, requesting flexible shifts and varied tasks.', 'Priya says the community’s actual needs should determine the activities.', 'They agree to contact the coordinator, plan two shifts with accessible tasks and transport information, and seek feedback afterwards.'],
    sample: 'The students are planning a community-garden volunteering day. Grace initially suggests a full Saturday of practical outdoor work. Sam supports the idea but points out that jobs, caring responsibilities and different physical abilities could prevent some students from participating. He recommends flexible shifts and a choice of activities. Priya adds that the garden’s own priorities should determine what volunteers do, rather than the students’ assumptions. Grace responds by offering to contact the coordinator and suggesting morning and afternoon shifts with lighter tasks. Sam asks for clear transport and equipment information. They ultimately agree to create a flexible, accessible plan after consulting the garden, and to check afterwards whether their contribution was useful.' }
]);
add('rts', [
  { title: 'Clarifying assignment feedback', text: 'Your tutor has returned an assignment with a comment saying that your argument needs stronger evidence. You are unsure what kind of evidence is missing. Speak to your tutor after class, ask for clarification and arrange a practical next step.',
    facts: ['Address the tutor directly and politely.', 'Explain uncertainty about the comment on evidence.', 'Ask which claim or type of evidence needs improvement.', 'Suggest a specific next step such as reviewing a paragraph or attending consultation.'],
    sample: 'Excuse me, could I ask about the feedback on my assignment? You mentioned that my argument needs stronger evidence, and I would like to understand how to improve it. Is there a particular claim that needs more support, or should I use a different type of source? If you have time, could we look at one paragraph together? Otherwise, I would be happy to bring it to your next consultation session.' },
  { title: 'Changing a group meeting', text: 'Your group has arranged to meet tomorrow afternoon, but your work shift has unexpectedly changed. You cannot attend at that time. Speak to your group members, explain the problem and suggest a fair way to keep the project moving.',
    facts: ['Speak directly to the group and explain the scheduling conflict.', 'Acknowledge the inconvenience without blaming others.', 'Offer an alternative time or remote contribution.', 'Commit to completing or sharing your allocated work.'],
    sample: 'Hi everyone, I’m sorry, but my work shift has changed unexpectedly and I can’t make tomorrow afternoon’s meeting. I know we have already organised the time, so I don’t want to hold up the project. Would an evening call work for you? If not, please go ahead without me. I’ll upload my research notes beforehand and respond to any questions afterwards, so my part of the work stays on schedule.' },
  { title: 'A noisy shared kitchen', text: 'You share a house with other students. Recently, late-night conversations in the kitchen have made it difficult for you to sleep before morning classes. Speak to your housemates, explain the effect on you and propose a reasonable agreement.',
    facts: ['Address housemates respectfully rather than accusing them.', 'Explain that late kitchen conversations affect sleep before morning classes.', 'Make a clear, reasonable request about late-night noise.', 'Invite agreement or an alternative that considers everyone’s needs.'],
    sample: 'Hi everyone, could we talk about noise in the kitchen at night? I’ve been finding it difficult to sleep when conversations continue late, and I have early classes several days a week. I know the kitchen is a shared space, so I’m not asking anyone to stop using it. Could we agree to keep voices low after ten thirty, or move longer conversations elsewhere? I’m happy to discuss a time that works for everyone.' },
  { title: 'Returning faulty headphones', text: 'You bought headphones from a shop three days ago. One side has stopped working, although you have used them normally. You have the receipt. Speak to the shop assistant, explain the issue and ask how it can be resolved.',
    facts: ['Address the assistant politely and identify the recent purchase.', 'Describe the specific fault without exaggeration.', 'Mention normal use and that the receipt is available.', 'Ask for a practical resolution or assessment without inventing legal guarantees.'],
    sample: 'Hello, I bought these headphones here three days ago, and one side has already stopped working. I’ve used them normally and checked them with another device, but the problem is still there. I have the receipt with me. Could you please check the fault and explain the available options? I would prefer a working replacement if possible, but I’m happy to hear how the shop can help resolve the issue.' },
  { title: 'Reporting a broken study-room projector', text: 'You have booked a study room for a group presentation rehearsal this afternoon. When you arrive, the projector will not switch on. Speak to the reception staff, explain the situation and ask for help without disrupting other students’ bookings.',
    facts: ['Politely explain that the booked room’s projector will not turn on.', 'State the need to rehearse a group presentation this afternoon.', 'Ask for technical help or an available alternative room or equipment.', 'Respect existing bookings and consider a practical backup.'],
    sample: 'Hello, our group has booked a study room for a presentation rehearsal this afternoon, but the projector won’t switch on. Could someone check it for us? If it cannot be fixed soon, is there an available room or a portable projector we could use? We don’t want to interfere with anyone else’s booking. If there is no alternative, we can rehearse from a laptop, but working projection equipment would be very helpful.' }
]);
for (const q of questions) {
  if (q.turns) q.text = q.turns.map(([speaker, text]) => speaker + ': ' + text).join('\n');
  if (['ra', 'rs'].includes(q.type)) q.sample = q.text;
}
module.exports = { version: 1, types, questions,
  source: 'https://www.pearsonpte.com/content/dam/ELL/pte/pearsonpte/pdfs/pte-academic-pdfs/PTE-Academic-Test-Taker-Score-Guide.pdf' };
